---
secrets:
  eso:
    vault:
      server: http://127.0.0.1:8200
      namespace: ""
      auth:
        kubernetes:
          mountPath: kind
          role: kind--tanzu-sync-secrets
    remote_refs:
      sync_git:
        ssh:
          private_key:
            key: kv-v2/dev/iterate-green/tanzu-sync/sync-git/ssh
            property: privatekey
          known_hosts:
            key: kv-v2/dev/iterate-green/tanzu-sync/sync-git/ssh
            property: knownhosts
      install_registry_dockerconfig:
        dockerconfigjson:
          key: kv-v2/dev/kind/tanzu-sync/install-registry-dockerconfig
